config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :app_configs
  resources :reports
end

app/models/app_config.rb
class AppConfig
  include Mongoid::Document

  module ConfigEnvs
    DEV = 'development'
    STG = 'staging'
    TEST = 'test'
    PRD = 'production'
    STG_PRD = [STG, PRD]
    ALL = [DEV, STG, TEST, PRD]
  end

  attr_accessor :development_configs, :staging_configs, :test_configs, :production_configs
  field :name, type: String
  field :type, type: String
  field :development, type: Hash
  field :staging, type: Hash
  field :test, type: Hash
  field :production, type: Hash

  validates_uniqueness_of :name
end

app/models/report.rb
class Report
  IGNORE_CONFIGS = ['SYSOP_USERNAME', '']
  def self.check_duplicates(type: '')
    configs = type.blank? ? AppConfig.order(name: 1) : AppConfig.where(type: type).order(name: 1)
    keys = {}
    configs.each do |conf|
      AppConfig::ConfigEnvs::STG_PRD.each do |e|
        env_config = conf.try(e)
        next if !env_config
        env_config.each do |k,v|
          next if v.blank? 
          keys[v] = {
            scopes: {},
            count: 0
          } if !keys[v]
          keys[v][:scopes][conf.name] = [] if !keys[v][:scopes][conf.name]
          keys[v][:scopes][conf.name] << "#{k}-#{e}"
          keys[v][:count] += 1
        end
      end
    end
    # duplicates = keys.select{|key, h| h[:scopes].keys.length >  1 }.values.map{|h| h[:scopes]}
    duplicates = keys.select{|key, h| h[:count] >  1 }.values.map{|h| h[:scopes]}
  end

end

app/controllers/app_configs_controller.rb
class AppConfigsController < ApplicationController
  before_action :set_app_config, only: [:show, :edit, :update, :destroy]

  # GET /app_configs
  # GET /app_configs.json
  def index
    @app_configs = AppConfig.order(name: 1)
  end

  # GET /app_configs/1
  # GET /app_configs/1.json
  def show
  end

  # GET /app_configs/new
  def new
    @app_config = AppConfig.new
  end

  # GET /app_configs/1/edit
  def edit
  end

  # POST /app_configs
  # POST /app_configs.json
  def create
    p app_config_params
    @app_config = AppConfig.new(app_config_params)

    respond_to do |format|
      if @app_config.save
        format.html { redirect_to @app_config, notice: 'App config was successfully created.' }
        format.json { render :show, status: :created, location: @app_config }
      else
        format.html { render :new }
        format.json { render json: @app_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_configs/1
  # PATCH/PUT /app_configs/1.json
  def update
    respond_to do |format|
      if @app_config.update(app_config_params)
        format.html { redirect_to @app_config, notice: 'App config was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_config }
      else
        format.html { render :edit }
        format.json { render json: @app_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_configs/1
  # DELETE /app_configs/1.json
  def destroy
    @app_config.destroy
    respond_to do |format|
      format.html { redirect_to app_configs_url, notice: 'App config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_config
      @app_config = AppConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_config_params
      app_params = params.require(:app_config).permit(:name, :type, :development_configs, :staging_configs, :test_configs, :production_configs)
      configs = nil
      enscrypt_infos = {}
      AppConfig::ConfigEnvs::ALL.each do |e|
        params_key = "#{e}_configs"
        next if !app_params[params_key.to_sym]
        configs = HashWithIndifferentAccess.new(YAML.load(app_params[params_key.to_sym]))
        if configs[e]
          configs[e].each do |k,v|
            configs[e][k] = Digest::SHA1.hexdigest(v.to_s)
          end
          app_params[e] = configs[e]
        end
      end

      app_params
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @columns = AppConfig.order(name: 1).pluck(:name)
    @duplicates = Report.check_duplicates
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/app_configs_helper.rb
module AppConfigsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/app_configs/_form.html.slim
= form_for @app_config do |f|
  - if @app_config.errors.any?
    #error_explanation
      h2 = "#{pluralize(@app_config.errors.count, "error")} prohibited this app_config from being saved:"
      ul
        - @app_config.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :development_configs
    = f.text_area :development_configs
  .field
    = f.label :staging_configs
    = f.text_area :staging_configs
    .field
    = f.label :test_configs
    = f.text_area :test_configs
  .field
    = f.label :production_configs
    = f.text_area :production_configs
  .actions = f.submit

app/views/app_configs/edit.html.slim
h1 Editing app_config

== render 'form'

=> link_to 'Show', @app_config
'|
=< link_to 'Back', app_configs_path

app/views/app_configs/index.html.slim
h1 Listing app_configs

=< link_to 'Report', reports_path
table
  thead
    tr
      th Name
      th Development?
      th Staging?
      th Production?
      th
      th
      th

  tbody
    - @app_configs.each do |app_config|
      tr
        td = app_config.name
        td = !!app_config.development
        td = !!app_config.staging
        td = !!app_config.production
        td = link_to 'Show', app_config
        td = link_to 'Edit', edit_app_config_path(app_config)
        td = link_to 'Destroy', app_config, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New App config', new_app_config_path

app/views/app_configs/new.html.slim
h1 New app_config

== render 'form'

= link_to 'Back', app_configs_path

app/views/app_configs/show.html.slim
p#notice = notice

p
  strong Name:
  = @app_config.name
p
  strong Type:
  = @app_config.type
p
  strong Development:
  = @app_config.development
p
  strong Test:
  = @app_config.staging
p
  strong Staging:
  = @app_config.test
p
  strong Production:
  = @app_config.production

=> link_to 'Edit', edit_app_config_path(@app_config)
'|
=< link_to 'Back', app_configs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConfigsManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.slim
h1 Listing Conflicts

=< link_to 'App Configs', app_configs_path
table.reports
  thead
    tr
      - @columns.each do |name|
        th = name
  tbody
    - @duplicates.each do |duplicate|
      tr
        - @columns.each do |name|
          td = duplicate[name]

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>